### ISSUE TITLE
STM32F103C8 support

### ISSUE THREAD

**Issue by ghost** [maarten-pennings/iAQcore#1]
Hello,

this is the first time i'm writing an issue on Github.

Well, i'm using your library with STM32duino and a "Blue Pill" STM32F103C8 - It's working fine out of the box! 
I just set the I2C clock speed to 100kHz and added a small ceramic capacitor (0.1 µF) between GND and VCC near the sensor.

Maybe you can add this MCU to the list of supported ones.

Best regards,

anwofis

**Comment by maarten-pennings** [comment]
Hi Anwofis,

Sorry for the late reply. I didn't even know people could submit issues on Github, so I never checked them. Now I know. I have added your comment to the list of tested boards (with a link to your github page, hope that is ok). Thanks for the feedback.

And I will try to put this "issue" to "close" :-)

Maarten

**Comment by RomeuCarvalhoPT** [comment]
Hi.
I'm using this lib on NodeMCU (ESP8266).
I'm having problems getting "good" values. I'm calling read() every 10s but most of the time I get error status, but once in a while I get OK status and good result.
Did you experienced this? What am I doing wrong?

Thank you very much

**Comment by maarten-pennings** [comment]
Hi @RomeuCarvalhoPT, are you using one of the standard examples. The line with setClockStretchLimit is very important for nodemcu.

**Comment by RomeuCarvalhoPT** [comment]
Hi @maarten-pennings .
Yep, I'm using the basic example.
I'm using a nodeMCU v3 esp-12 on pins D1 and D2.
I guess that this might be related to not have pullup resistors on D1 and D2.
I still didn't test with resistors because I have none in hand.
Did you ever tried with this boar without pullups?

Thank you

**Comment by maarten-pennings** [comment]
I hardly ever use pull-ups. The ESP has internal pull-ups that are good enough. 

Can you show the output when running the basic example?
