### ISSUE TITLE
Setting SDA and SCL pins

### ISSUE THREAD

**Issue by ghost** [maarten-pennings/iAQcore#4]
Hello Maarten,

The examples show a function being called to setup Wire:
```
Wire.begin(/*SDA*/D2,/*SCL*/D1);
```

When using this library in PlatformIO with the Arduino framework I had to set SDA and SCL separately:
```
Wire.setSDA(SDA);
Wire.setSCL(SCL);
Wire.begin();
```

Based on current Arduino documentation, they might've changed Wire's 'begin' function to only accept an address rather than set SDA and SCL pins.

After this change is made, the code successfully runs on an STM32L031K6 microcontroller.

**Comment by maarten-pennings** [comment]
The wire.begin is a bit messy over the various libraries (how to pass the sda/scl lines).
Sorry for - but I can't fix that.
Happy you got it working!

**Comment by maarten-pennings** [comment]
I did add a comment in iAQcore-basic.ino

**Comment by ghost** [comment]
Thank you!
